# config.py

# === General Settings ===
# === Strategy Toggles ===
ENABLE_RSI = True
ENABLE_EMA = True
ENABLE_MACD = True
ENABLE_SMC = True
ENABLE_CANDLE_FILTER = True
ENABLE_FIBONACCI = True
ENABLE_SUPPORT_RESISTANCE = True
ENABLE_TRENDLINE = True
ENABLE_SMART_MONEY = True
ENABLE_RETRY_ON_FAILURE = True
RETRY_ATTEMPTS = 3
RETRY_DELAY_SECONDS = 10
ENABLE_SIGNAL_REPEAT_PROTECTION = True
SIGNAL_INTERVAL_SECONDS = 600  # 10 minutes
USE_BOS = True
USE_OB = True
USE_FVG = True




# === RSI Settings ===
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30

# === EMA Settings ===
EMA_PERIOD = 14

# === MACD Settings ===
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

# === Risk Management ===
LOT_SIZE = 0.1
STOP_LOSS_DOLLAR = 50
TAKE_PROFIT_DOLLAR = 150
MIN_RR_RATIO = 2  # 1:2 Risk:Reward

# === No Signal Alert ===
ENABLE_NO_SIGNAL_ALERT = True
NO_SIGNAL_TIMEOUT_HOURS = 12

# === Retry Logic ===
MAX_RETRY_ATTEMPTS = 3
RETRY_DELAY_SECONDS = 10

# === Telegram ===
TELEGRAM_BOT_TOKEN = "7067823429:AAGNC-E4gI8CaM0KlbonziViY17g4otB54A"
TELEGRAM_CHAT_ID = "2069276522"
ENABLE_TELEGRAM_ALERTS = True  # Set to False if you want to disable telegram alerts
TELEGRAM_RETRY_ATTEMPTS = True
TELEGRAM_BOT_NAME = "DGFXBot"  # You can change the name to whatever fits your brand
TELEGRAM_SEND_CHART_IMAGE = True  # or False if you don't want to send chart images
TELEGRAM_BOT_STATUS_MESSAGE = "DGFXBot is online and scanning the markets!"  # You can change the message
# Time interval between signals in seconds
SIGNAL_INTERVAL_SECONDS = 600  # 10 minutes





# === GENERAL SETTINGS ===
BOT_NAME = "DGFXBot"
ENABLE_LOGGING = True
LOG_TO_CSV = True
CSV_FILE_PATH = "signals_log.csv"
TIMEZONE = "Africa/Lagos"
TIMEFRAME = "H4"  # or any other timeframe like "H1", "M30", "M15", "D1"


# === SYMBOL SETTINGS ===
SYMBOLS = ["EURUSDm", "GBPUSDm", "USDJPYm", "BTCUSDm", "XAUUSDm", "USDCADm", "AUDUSDm", "USDCHFm", "EURGBPm", "EURJPYm", "GBPJPYm"]

# === SIGNAL SENDING SETTINGS ===
ENABLE_AUTO_SIGNAL_SENDING = True
TELEGRAM_BOT_TOKEN = "7067823429:AAGNC-E4gI8CaM0KlbonziViY17g4otB54A"
TELEGRAM_CHAT_ID = "2069276522"  # Replace with real chat ID
SIGNAL_SEND_RETRIES = 3
RETRY_DELAY_SECONDS = 5
SIGNAL_PREFIX = "📊 DGFXBot Signal Alert"
NO_SIGNAL_ALERT_INTERVAL_HOURS = 12

# === STRATEGY CONTROL FLAGS ===
USE_SMC = True
USE_CANDLESTICK_PATTERNS = True
USE_TRENDLINE_ANALYSIS = True
USE_FIBONACCI_ANALYSIS = True
USE_TECHNICAL_INDICATORS = True
USE_SENTIMENT_ANALYSIS = True
USE_AI_SIGNAL_SCORING = True

# === SMART MONEY CONCEPT (SMC) ===
ENABLE_SMC_FILTER = True
MIN_VOLUME_THRESHOLD = 1_000_000
ENABLE_LIQUIDITY_GRAB_CHECK = True
ENABLE_ORDER_BLOCK_DETECTION = True
ENABLE_BREAK_OF_STRUCTURE_CHECK = True
ENABLE_FAIR_VALUE_GAP_CHECK = True

# === CANDLESTICK PATTERNS ===
ENABLE_CANDLESTICK_FILTER = True
REQUIRED_PATTERN_CONFIRMATION = True
PATTERNS_TO_RECOGNIZE = [
    "bullish_engulfing",
    "bearish_engulfing",
    "hammer",
    "inverted_hammer",
    "shooting_star",
    "doji",
    "morning_star",
    "evening_star",
    "piercing_line",
    "dark_cloud_cover"
]

# === TRENDLINE DETECTION / SUPPORT-RESISTANCE ===
ENABLE_TRENDLINE_DETECTION = True
TRENDLINE_LOOKBACK = 30
SUPPORT_RESISTANCE_WINDOW = 50
TRENDLINE_CONFIRMATION_REQUIRED = True

# === FIBONACCI SETTINGS ===
ENABLE_FIBONACCI_ANALYSIS = True
FIBONACCI_LOOKBACK = 100
FIBONACCI_RETRACEMENT_LEVELS = [0.236, 0.382, 0.5, 0.618, 0.786]
FIB_CONFLUENCE_REQUIRED = True
# Threshold for considering price to be near a Fibonacci level (1% by default)
FIBONACCI_PROXIMITY_THRESHOLD = 0.01


# === TECHNICAL ANALYSIS SETTINGS ===
EMA_PERIODS = [20, 50, 200]
RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30

# === SENTIMENT ANALYSIS ===
ENABLE_SENTIMENT_ANALYSIS = True
NEWSAPI_KEY = "1e7d1c0997e0421dbd4ce2049b982888"
SENTIMENT_MIN_SCORE = 0.2

# === AI LEARNING ===
ENABLE_AI_SIGNAL_SCORING = False  # Disabled temporarily due to OpenAI quota
ENABLE_WIN_LOSS_LEARNING = True
ENABLE_ADAPTIVE_SCORING = True

# === BACKTESTING ===
ENABLE_BACKTESTING = True
BACKTEST_LOOKBACK_DAYS = 90
BACKTEST_MIN_WINRATE = 0.6
BACKTEST_ENABLE_AI_OPTIMIZATION = True

# === PNL TRACKING & SL/TP ===
ENABLE_LIVE_TRADE_MONITORING = True
DEFAULT_RISK_PER_TRADE = 0.01
DEFAULT_LOT_SIZE = 0.1
STOP_LOSS_USD = 50
TAKE_PROFIT_USD = 150
MINIMUM_RR_RATIO = 2

# === DASHBOARD SETTINGS ===
ENABLE_DASHBOARD = True
DASHBOARD_PORT = 8501
SHOW_CHARTS = True
REFRESH_INTERVAL_SECONDS = 60

# === AI SCORING PLACEHOLDER ===
DEFAULT_AI_SCORE = 0.5

# === Currency Pairs to Monitor ===
MONITORED_PAIRS = [
    "EURUSDm", "GBPUSDm", "USDJPYm", "USDCHFm", "USDCADm",
    "AUDUSDm", "NZDUSDm", "EURJPYm", "GBPJPYm", "BTCUSDm",  # BTCUSDm added
    "XAUUSDm", "XAGUSDm", "EURNZDm", "EURCADm", "GBPCHFm",
    "GBPCADm", "AUDJPYm", "AUDNZDm", "NZDJPYm", "USDZARm"
]

# config.py
DASHBOARD_REFRESH_INTERVAL = 60  # refresh every 60 seconds (you can tweak this)
SIGNAL_LOG_CSV_PATH = "pnl_log.csv"

csv_path = SIGNAL_LOG_CSV_PATH
refresh_interval = DASHBOARD_REFRESH_INTERVAL


